[project]
protostar-version = "0.9.0"
lib-path = "contracts"

[contracts]
world = ["contracts/world/World.cairo"]

# Shared Configuration Profile
[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"
chain-id = 1536727068981429685321

[profile.testnet.project]
network = "testnet"

[format]
target = ["contracts", "tests"]
ignore-broken = true  
